name: Auto publish new version 

on:
  push:
    branches: [main]


jobs:
  publish:
    if: github.repository == 'stavenko/cargo-ws-version'
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy
      - name: Setup | Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Auto publish on version changed
        uses: seunlanlege/cargo-auto-publish@2 
        env: 
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
