name: Auto publish new version 

on:
  push:
    branches: [main]


jobs:
  publish:
    if: github.repository == 'stavenko/cargo-ws-version'
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy
      - name: Setup | Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Auto publish on version changed
        env: 
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: |
          env;
          cargo install tomlq
          git checkout HEAD~1;
          export PREV=`tomlq "package.version" -f Cargo.toml`;
          git checkout main;
          export NEXT=`tomlq "package.version" -f Cargo.toml`;
          echo "Version prev $PREV, version next $NEXT";
          if [ "$NEXT" != "$PREV" ]
          then
            echo "publish package version changed";
            cargo publish --token ${{ secrets.CARGO_TOKEN }}
          fi
