name: Check

on:
  push:
    branches: [ feature/**, hotfix/** ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup | Sources
      uses: actions/checkout@v2
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
        components: clippy
    - name: Check using clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
