name: Check

on:
  push:
    branches: [ feature/**, hotfix/** ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: rust:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install clippy
      run: rustup component add clippy;
    - name: Check using clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
